services:
  redis-cache:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - stockpulse-net
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    
  cache:
    build:
      context: . # path to ingestion Dockerfile
    container_name: cache_service
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - stockpulse-net
    depends_on:
      - redis-cache  

networks:
  stockpulse-net:
    external: true

volumes:
  redis-data:
    driver: local